- name: Generate patch status report
  hosts: all
  tasks:
    - name: Check general patch status
      script: patch-status.sh {{ ansible_os_family }}
      register: patch_status

    - name: Generate patch status report
      template: src=patch-report.j2 dest="{{ report_dest }}"
      delegate_to: "{{ report_host }}"
      run_once: true

    - debug:
        msg: "<a href=\"{{ report_url }}\">Report Available Here</a>"
      when: report_url is defined
      run_once: true
