- name: Update Linux operating system
  hosts: all
  tasks:
    - name: Update Debian family OS
      apt:
        update_cache: yes
        upgrade: yes
      when: ansible_os_family == "Debian"

    - name: Update RedHat family OS
      yum:
        name: '*'
        state: latest
        update_cache: yes
      when: ansible_os_family == "RedHat"

    - name: Update Suse family OS
      zypper:
        name: '*'
        state: latest
        type: patch
        update_cache: yes
      when: ansible_os_family == "Suse"

    - name: Check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: Reboot server
      shell: sync && shutdown -r now "Triggered by Ansible update"
      async: 1
      poll: 0
      ignore_errors: true
      when: reboot_required.stat.exists

    - name: Waiting for the machine to come back up
      local_action: wait_for host={{ ansible_host }} state=started port=22 delay=30
      become: no
      when: reboot_required.stat.exists
